package automobile.cars.model.entity;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

public class VehicleColorTest {

    @Test
    void testNotNullConstraints() {
        // Act
        VehicleColor color = new VehicleColor();

        // Assert
        assertNull(color.getId()); // Assuming id is null until generated by the database
        assertNull(color.getPaint()); // Expecting paint to be null initially
    }

    @Test
    void testGettersAndSetters() {
        // Arrange
        VehicleColor color = new VehicleColor();
        Long id = 1L;
        String paint = "Red";

        // Act
        color.setId(id);
        color.setPaint(paint);

        // Assert
        assertNotNull(color.getId());
        assertNotNull(color.getPaint());
    }
}
