package automobile.cars.model.entity;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class VehicleComfortTest {

    @Test
    void testNotNullConstraints() {
        // Act
        VehicleComfort comfort = new VehicleComfort();

        // Assert
        assertNull(comfort.getId()); // Assuming id is null until generated by the database
        // Asserting all boolean properties are initially false
        assertFalse(comfort.isAirConditioning());
        assertFalse(comfort.isCruiseControl());
        assertFalse(comfort.isPowerSteering());
        assertFalse(comfort.isTiltSteeringWheel());
        assertFalse(comfort.isTelescopingSteeringWheel());
        assertFalse(comfort.isRearDefrost());
        assertFalse(comfort.isRemoteTrunkRelease());
        assertFalse(comfort.isRemoteEngineStart());
        assertFalse(comfort.isHeatedSteeringWheel());
        assertFalse(comfort.isHeatedMirrors());
    }

    @Test
    void testGettersAndSetters() {
        // Arrange
        VehicleComfort comfort = new VehicleComfort();
        Long id = 1L;

        // Act
        comfort.setId(id);
        comfort.setAirConditioning(true);
        comfort.setCruiseControl(true);
        comfort.setPowerSteering(true);
        comfort.setTiltSteeringWheel(true);
        comfort.setTelescopingSteeringWheel(true);
        comfort.setRearDefrost(true);
        comfort.setRemoteTrunkRelease(true);
        comfort.setRemoteEngineStart(true);
        comfort.setHeatedSteeringWheel(true);
        comfort.setHeatedMirrors(true);

        // Assert
        assertNotNull(comfort.getId());
        assertTrue(comfort.isAirConditioning());
        assertTrue(comfort.isCruiseControl());
        assertTrue(comfort.isPowerSteering());
        assertTrue(comfort.isTiltSteeringWheel());
        assertTrue(comfort.isTelescopingSteeringWheel());
        assertTrue(comfort.isRearDefrost());
        assertTrue(comfort.isRemoteTrunkRelease());
        assertTrue(comfort.isRemoteEngineStart());
        assertTrue(comfort.isHeatedSteeringWheel());
        assertTrue(comfort.isHeatedMirrors());
    }
}
